//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHungerAssignment.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderList
    {
        public int Id { get; set; }
        public string Res_Name { get; set; }
        public string Res_Location { get; set; }
        public string Food_Name { get; set; }
        public string Max_Time { get; set; }
        public string Order_Status { get; set; }
    }
}
